
2025-06-27 21:58:05,899 ERROR: Uncaught exception:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/app.py", line 27, in <module>
    main()
    ~~~~^^
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/app.py", line 22, in main
    win = LogTriageWindow()
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/mainwindow.py", line 22, in __init__
    self.init_ui()
    ~~~~~~~~~~~~^^
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/mainwindow.py", line 98, in init_ui
    self.init_menus()
    ~~~~~~~~~~~~~~~^^
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/mainwindow.py", line 363, in init_menus
    self.update_recent_menu()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/mainwindow.py", line 514, in update_recent_menu
    folders = self.load_recent_folders()
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/mainwindow.py", line 128, in load_recent_folders
    return self.settings.value(RECENT_FOLDERS_KEY, [], type=list)
                               ^^^^^^^^^^^^^^^^^^
NameError: name 'RECENT_FOLDERS_KEY' is not defined

2025-06-27 22:00:20,775 ERROR: Uncaught exception:
Traceback (most recent call last):
  File "/Users/johnsonamalraj/Documents/github/asic_dv/dev_tools/scripts/log_triage_dev/logtriage/mainwindow.py", line 972, in show_author
    QMessageBox.information(self, "Author",
    ^^^^^^^^^^^
NameError: name 'QMessageBox' is not defined

